### ISSUE TITLE
Include without Composer

### ISSUE THREAD

**Issue by emresaracoglu** [ZzAntares/ProxmoxVE#20]
Hello, how I can Include files without Composer?

**Comment by ZzAntares** [comment]
You can't, you shouldn't, this project has dependencies on other packages, dependencies are managed by composer. If you must, then you could `composer install` this package in an empty folder, copy the generated `vendor` folder to your project, and require the `autoload.php` and you will still need to reference classes by their namespace.

Or, you could clone this project, attempt to use it without installing dependencies and fix every exception you find in the way, most of them referred to guzzle classes. At that point you will need also clone the correct `guzzle` version, and once again fix the exceptions you found as guzzle package also has dependencies, after you require all the referenced classes it should work.

I'm curious, why not to use composer? it doesn't even enforce a project structure, is not incompatible with legacy code, is the main reason why PHP community is now better.
