### ISSUE TITLE
It's not work #27 is old post for this problem

### ISSUE THREAD

**Issue by MrKampf** [ZzAntares/ProxmoxVE#28]
Sorry, because it's not work :/
http://prntscr.com/jauyi8
This is my Code. The "new Proxmox" work, by the function loading information i become information becaus stop dont work (Login with root user)
http://prntscr.com/jauz7n Login data Loading work

Now http://prntscr.com/jauzhz i dont become true back and the server stop not.
equal is this by start. The type is LXC Proxmox version is "Virtual Environment 5.1-41"

Thanks for all answers and sorry for my bad english

**Comment by ZzAntares** [comment]
Hello! you can still comment on closed issues, so there's no need to open a new one, I'm going to close this one, discussion continues in #27
