### ISSUE TITLE
Merge Dev-guzzle6 to master branch?

### ISSUE THREAD

**Issue by citadelnetworks** [ZzAntares/ProxmoxVE#30]
I noticed for PHP 7.x you need to get "dev-guzzle6". Why not make that the default one?

**Comment by ZzAntares** [comment]
Yes, that's a work in progress, I haven't had the time to make the release, but I want it to happen soon. I'll leave this issue open as a reminder.

**Comment by ZzAntares** [comment]
Done [v4.0.0](https://github.com/ZzAntares/ProxmoxVE/releases/tag/v4.0.0).
