### ISSUE TITLE
Problem with composer install

### ISSUE THREAD

**Issue by blu3bird23** [ZzAntares/ProxmoxVE#31]
Hello, i got this error from composer:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package zzantares/proxmoxve No version set (parsed as 1.0.0) is satisfiable by zzantares/proxmoxve[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

PHP:

```
PHP 5.6.30 (cli) (built: Oct 29 2017 20:30:32) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

composer.json:

```
{
    "name": "zzantares/proxmoxve",
    "type": "library",
    "description": "A simple PHP 5.4+ Proxmox API client.",
    "keywords": ["Proxmox", "API", "KVM", "OpenVZ", "Virtualization"],
    "homepage": "https://github.com/ZzAntares/ProxmoxVE",
    "license": "MIT",

    "authors": [
        {
            "name": "César Muñoz",
            "email": "zzantares@gmail.com",
            "role": "Developer"
        }
    ],

    "support": {
        "issues": "https://github.com/ZzAntares/ProxmoxVE/issues",
        "source": "https://github.com/ZzAntares/ProxmoxVE"
    },

    "require": {
        "php": ">=5.3.0",
        "lib-curl": "*",
        "guzzlehttp/guzzle": "~4.0",
        "zzantares/proxmoxve": "~3.0"
    },

    "require-dev": {
        "phpunit/phpunit": "~4.1",
        "squizlabs/php_codesniffer": "1.*"
    },

    "autoload": {
        "psr-4": {
            "ProxmoxVE\\": "src/"
        }
    }

}
```

how can i fix this issue?

Thanks.

**Comment by blu3bird23** [comment]
got this fixed by using composer global require zzantares/proxmoxve:3.0 on mac :) 👍

**Comment by ZzAntares** [comment]
Hi, just as a note though. It seems to me that you tried to install this package using a modified version of the `composer.json` file in the package itself. That's not the way, you're supposed to install this package (unless you plan to contribute to the project, and even then you should use the cloned file).

The `composer.json` that you need to modify is the one in your own PHP project, and add `"zzantares/proxmoxve": "~3.0"` as a dependency for your project in the `require` section (just as the readme states). Note that if you don't have a `composer.json` file in your project, it can be created using `composer init`.

More over, this is a library and it shouldn't be installed globally, unless you really want that (which will be odd). I just did setup a docker with your specific PHP version and installed the library locally (as it should) without problems using the command `composer require zzantares/proxmoxve ~3.0`.

Of course, it may happened I misunderstood your issue, I'm glad it's solved, but if not feel free to re-open 😉 .
