### ISSUE TITLE
How auth user with PHP

### ISSUE THREAD

**Issue by ZeroCrazy** [ZzAntares/ProxmoxVE#38]
Hello guys!
I'm trying to authenticate a user in all possible ways but I can't ... can you help me please? This is my current configuration (I paste the code here because it is long): https://pastebin.com/uCJ5XgFd .
That is, the system detects that the user exists, but when I try to connect to the VNC it tells me that there is no connection :(

**Comment by Cr4zyFl1x** [comment]
Hi!
Have a look at the following comment: https://github.com/ZzAntares/ProxmoxVE/issues/17#issuecomment-581190348 maybe it's the solution fpr your problem.

**Comment by ZzAntares** [comment]
For others looking how to setup VNC [see this](https://github.com/ZzAntares/ProxmoxVE/issues/17#issuecomment-688937674).
