### ISSUE TITLE
PMG Support?

### ISSUE THREAD

**Issue by skipworkgh** [ZzAntares/ProxmoxVE#40]
The Proxmox Mail Gateway API requires the name of the authentication cookie to be PMGAuthCookie instead of PVE's PVEAuthCookie.

[I've added an extra option to the credentials object to support this](https://github.com/skipworkgh/ProxmoxVE/tree/pmg-support). 

I'm not sure if this is still within the scope of this library. If it is I'm happy to create a PR for it.

**Comment by ZzAntares** [comment]
Awesome!, if it's backwards compatible we'll take it.

**Comment by skipworkgh** [comment]
It is. I've added an entry to the readme file to show using it for the MailGateway API. Tests are included as well.

**Comment by skipworkgh** [comment]
@ZzAntares could you take a look at the PR?

**Comment by ZzAntares** [comment]
Merged, apologies for the time hehe I really don't care much about PHP anymore 😛
