### ISSUE TITLE
Guzzle ^7.0 support ?

### ISSUE THREAD

**Issue by GothShoot** [zzantares/ProxmoxVE#45]
Hello,

Possible to have a new release with guzzlehttp/guzzle in version ^7.0 ?
Many packages require them but your lib doesn't support over 6.5 😞 

Thanks

**Comment by acairon** [comment]
im having the same exact problem

**Comment by GothShoot** [comment]
Someone have opened the #44 PR for that but not work 😞

**Comment by GothShoot** [comment]
The master support guzzle ^7.0.

Use dev-master tag or just patient for a release.

**Comment by GothShoot** [comment]
@zzantares Can you give me right to update this lib and release compat with newest PHP ?

**Comment by zzantares** [comment]
Thanks @GothShoot, check your email, the invite was sent :)

**Comment by GothShoot** [comment]
Thanks :smile:

**Comment by iandk** [comment]
Hi, 
Installing the package via composer still doesn't work.
Can anyone guide me on how to install this package on a Laravel 9 Project?

Thanks!

**Comment by GothShoot** [comment]
@iandk Please, open issue separately, and tell me what's happened, i probably can help you :smiley:

**Comment by noxomix** [comment]
Just for all the People also Struggeling to install it in Laravel 9 (which needs obviously Guzzle 7.2) the solution is:

`composer require zzantares/proxmoxve dev-master`

Then it should be work :)

**Comment by noxomix** [comment]
Ou and @zzantares can you please make a new release for the current dev-master? Because exactly this release works with Guzzle 7, but when someday sb changes anything in the Main branch, it also could be possible that it is not working anymore or causing issues. So can you just make a 4.0.1 release or lets say you name it guzzle7-possible or something like that, so that i could be secure that whenever i setup my laravel project in the future the current (unchanged) dev-master will be installed by composer ;)

Would be pretty nice.

**Comment by GothShoot** [comment]
Hello, i probably can do this, let me check if master branch is ready for a release and i notify you when is okay :)

**Comment by GothShoot** [comment]
Fixed by new release v4.1.0 allow support of guzzle 7, i plan to release a v5 for fully drop previous v6 and port support of php higher by dropping old package compatibility (and probably nice other things)

Thanks for relaunch about guzzle @hall-of-code !

**Comment by noxomix** [comment]
Thank you very Much. Unfortunatly 4.1 is not avaible in Composer Package, please hit the "Update" button on Packagist or so :)

**Comment by zzantares** [comment]
Thank you so much for the support @GothShoot! 4.1 should be available now, I've updated it in packagist.

btw, I tried to add you as a project maintainer in packagist.org but it seems `GothShoot` refers to a different user account or is that your account?
