### ISSUE TITLE
Planning on any dependency updates?

### ISSUE THREAD

**Issue by Caroga** [ZzAntares/ProxmoxVE#6]
Hi,

As I tried installing your bundle I got the following composer message:
```
$ composer require zzantares/proxmoxve
Using version ^3.0 for zzantares/proxmoxve
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for zzantares/proxmoxve ^3.0 -> satisfiable by zzantares/proxmoxve[v3.0.0].
    - Conclusion: remove guzzlehttp/guzzle 6.0.2
    - Conclusion: don't install guzzlehttp/guzzle 6.0.2
    - zzantares/proxmoxve v3.0.0 requires guzzlehttp/guzzle ~4.0 -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3].
    - Can only install one of: guzzlehttp/guzzle[4.0.0, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.0.1, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.0.2, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.0, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.1, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.2, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.3, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.4, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.5, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.6, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.7, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.1.8, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.2.0, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.2.1, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.2.2, 6.0.2].
    - Can only install one of: guzzlehttp/guzzle[4.2.3, 6.0.2].
    - Installation request for guzzlehttp/guzzle == 6.0.2.0 -> satisfiable by guzzlehttp/guzzle[6.0.2].
```
Are you planning on updating these dependencies any time soon ?

**Comment by ZzAntares** [comment]
Hello, sure!, I'll work on it this weekend.

Stay tuned.

**Comment by Caroga** [comment]
Hi ! thanks! If you need anything, please tell. If I have the time I could maybe help you out if possible. Currently working to get the V2.1.1 working though.

**Comment by ZzAntares** [comment]
The work is done, build is passing but I need your help to do a real test on a proxmox server (right now I don't have any):

First use the `dev-devel` version, install with: `composer require zzantares/proxmoxve dev-devel`.

Then as long as this code works we will know everything is fine (set your credentials).

```
<?php
require_once 'vendor/autoload.php';
use ProxmoxVE\Proxmox;

// Set your credentials here!
$credentials = [
    'hostname' => '',  // or IP
    'username' => '',
    'password' => '',
];

$proxmox = new Proxmox($credentials);
$allNodes = $proxmox->get('/nodes');

print_r($allNodes);
```

If you can see the nodes, then I will know all it's ok and I will release the new version. If you can help would be great.

Thanks!

**Comment by Caroga** [comment]
Great work. I will perform the test for you. I will check back in within the hour.

**Comment by Caroga** [comment]
Hi, I just tried my first test, and I get a `null` object in return. I have not yet debugged it properly but I thought you should know.
```
<?php

namespace CarogaNet\Test\TestBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use ProxmoxVE\Proxmox;

class DefaultController extends Controller
{
    /**
     * @Route("/")
     * @Template()
     */
    public function indexAction()
    {

        print('--- starting proxmox api check');

        $credentials = [
            'hostname' => 'galatea.exsilia.net',  // or IP
            'username' => 'root',
            'password' => '87986554',
        ];
        print('--- proxmox credentials set');

        $proxmox = new Proxmox($credentials);
        print('--- proxmox object instantiated');

        $allNodes = $proxmox->get('/nodes');
        print('--- proxmox api call to retrieve /nodes');

        var_dump($allNodes);

        return array();
    }

}
```

**Comment by Caroga** [comment]
I just had time to start debugging and I found that my authentication was unsuccessful. This problem occurred when using your v2.1.1 library as well so it might just be my own server. I have no clue yet.

**Comment by ZzAntares** [comment]
Ok, thanks for your feedback, I'll setup a proxmox server in a virtualbox machine (if it's possible) to test if at least authentication is working.

**Comment by Caroga** [comment]
Hi!

Today i'll also take a look into it. Maybe find something that has to do with my proxmox installation. I assume API access is on by default ? No special setup required?

Any progress?

**Comment by ZzAntares** [comment]
Seems it works but I can not test it, I get:

```
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 56: SSLRead() return error -9806 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /Users/antares/Documents/borrame/algo/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:169
```

I think is due to the certificates may be now is enforced, I'll add SSL support to see if that fix it. This is going to require more time =S

**Comment by Caroga** [comment]
I have this afternoon available to assist you on this matter. I will checkout branch "devel".
Any updates which I need to know ? 

I will try to add the SSL support and see what happens.

**Comment by Caroga** [comment]
Okay this is really weird. When using this inside my vagrant container I cannot login, when using this outside my vagrant container, it works and I get a result.

```php
<?PHP

$autoload = '/home/caroga/projects/ProxmoxVE/vendor/autoload.php';

if (!file_exists($autoload)) {
    echo "Please install project runing:\n\tcomposer install\n\n";
    exit("composer what?\n\thttps://getcomposer.org/download/\n\n");
}

$loader = include $autoload;
$loader->addPsr4('ProxmoxVE\\', __DIR__);
$loader->addPsr4('ProxmoxVE\\CustomClasses\\', __DIR__ . '/CustomClasses');

use ProxmoxVE\Proxmox;

$credentials = [
    'hostname' => 'galatea.exsilia.net',  // Also can be an IP
    'username' => 'root',
    'password' => 'gibberish',
    'realm' => 'pam',
    'port' => '8006',
];

// Then simply pass your credentials when creating the API client object.
$proxmox = new Proxmox($credentials);

$allNodes = $proxmox->get('/nodes');

print_r($allNodes);
```

outputs the following:

```bash
Array
(
    [data] => Array
        (
            [0] => Array
                (
                    [disk] => 111103401984
                    [cpu] => 0.015096651240247
                    [maxdisk] => 476006039552
                    [maxmem] => 8367427584
                    [node] => galatea
                    [maxcpu] => 4
                    [level] => 
                    [uptime] => 7266725
                    [id] => node/galatea
                    [type] => node
                    [mem] => 4166397952
                )

        )

)
```

**Comment by ZzAntares** [comment]
May be is the PHP version producing that behaviour since guzzlehttp/guzzle 6.0 requires 5.5 or greater. Weird in deed sorry the delay but ultimately I don't have time to fix this. Hope this weekend work on it.

**Comment by Caroga** [comment]
No problem, i completely understand. I to have the same lack of time for such projects.
I think it has more to do with the used interface of the machine, since it's provisioned with 5.6.
I am now looking for a way to configure the default network interface, as this is the only difference between my laptop and vagrant env.

**Comment by ZzAntares** [comment]
sure why not if you find it useful would be great, thanks.

On the other hand I did some test in virtual proxmox server and indeed SSL is the issue, the weird thing is that I'm [telling guzzle not to verify ssl](https://github.com/ZzAntares/ProxmoxVE/blob/master/src/Proxmox.php#L114) which I think it translates to the `CURLOPT_SSL_VERIFYHOST ` option in the underlying curl instance (maybe I'm wrong).

As soon as any request works other than the login call, we'll be ready to publish the new version.

**Comment by Caroga** [comment]
Sorry for long delay, I messed up my Arch installation this weekend by compiling some kernel modules... I just finished installing my system, should be in working order again. 

I think that the reason for it not to work yet is that verify host should go along with verify peer (CURLOPT_SSL_VERIFYPEER). Maybe there is another flag needed somewhere. I will take a look into it.

**Comment by Caroga** [comment]
I just did a get request for the status and it returned nicely.
```Array
(
    [data] => Array
        (
            [cpu] => 0
            [rootfs] => Array
                (
                    [free] => 229907439616
                    [used] => 110959403008
                    [total] => 476006039552
                    [avail] => 340866842624
                )

            [idle] => 0
            [pveversion] => pve-manager/3.4-9/4b51d87a
            [loadavg] => Array
                (
                    [0] => 0.00
                    [1] => 0.00
                    [2] => 0.00
                )

            [memory] => Array
                (
                    [free] => 4184875008
                    [used] => 4182552576
                    [total] => 8367427584
                )

            [ksm] => Array
                (
                    [shared] => 0
                )

            [wait] => 0
            [swap] => Array
                (
                    [free] => 15550701568
                    [used] => 839585792
                    [total] => 16390287360
                )

            [uptime] => 7673631
            [kversion] => Linux 2.6.32-39-pve #1 SMP Fri May 8 11:27:35 CEST 2015
            [cpuinfo] => Array
                (
                    [hvm] => 1
                    [sockets] => 1
                    [mhz] => 2393.798
                    [user_hz] => 100
                    [model] => Intel(R) Xeon(R) CPU           X3220  @ 2.40GHz
                    [cpus] => 4
                )

        )

)
```

**Comment by Caroga** [comment]
Any status updates? I will be continuing my project next week, so if needed I can test some other stuff as well ?

**Comment by Caroga** [comment]
Bumping, without being rude xD

**Comment by ZzAntares** [comment]
Hello, I'm very sorry I haven't look at this issue in a while. You said you made it work but I don't know if you fix some code, if so, can you send the PR?

**Comment by ZzAntares** [comment]
FYI: The `devel` branch with guzzle v6 is working well, the only issue is for people in MacOSX (like me) you'll get an exception about SSL Read error ([read more about this](https://github.com/guzzle/guzzle/issues/819)) so the fix is to ensure your PHP and specifically the libcurl is compiled with openssl support. [Mac users can follow this guide](https://www.farces.com/wikis/naked-server/php/php-openssl/), under linux just be sure to have the last update of openssl.

Since the master branch does not have this issue, I do not see the need to merge develop changes in there (is working well), but anyone interested in the library using guzzle 6 can require the devel branch in his `composer.json` file.
