### ISSUE TITLE
issue in creating a vm

### ISSUE THREAD

**Issue by avi123nash** [ZzAntares/ProxmoxVE#7]
I tried you api it works fine...But when i was creating a OpenVZ container using create function the data  is displayed, but somehow it does not create CT...:(...Can you provide some help

$vps_creation = $proxmox->create('/nodes/'.$nodename.'/openvz -vmid '.$params['vmid'].' -hostname '.$params['hostname'].' -storage '.$params['storage'].' -password '.$params['password'].' -ostemplate '.$params['ostemplate'].' -memory '.$params['memory'].' -swap '.$params['swap'].' -disk '.$params['disk'].' -cpus '.$params['cpus'].' -ip_address '.$params['ip_address'], $params);

This is the command i tried...

**Comment by ZzAntares** [comment]
Hi, can you provide the given response? It may contain more info about the issue.

Thanks

**Comment by avi123nash** [comment]
The output i get says that the vps is created but there isnt any.....

Thanks.

**Comment by ZzAntares** [comment]
I know this is a very late response, but I for others reading, the mistake here is that you can't pass the params in flags directly in the string as the first argument, any params should come as a second argument in an associative array, you can see an example in the [Creating resources section](https://github.com/ZzAntares/ProxmoxVE/blob/master/doc/create.md) file.

**Comment by avi123nash** [comment]
Hi,
  Its okay even if it was late, still appreciated the help...:D...And yes i understood your answer, what you mean send it as a post array which is associative array, then it will execute successfully.
