### ISSUE TITLE
issue with OS template

### ISSUE THREAD

**Issue by avi123nash** [ZzAntares/ProxmoxVE#8]
hey can you brief me about the architecture for os templates which proxmox supports??

I mean does it support only "i386" and "amd64"? or it goes with x86_64 as well??

I am trying to create Openvz container using api but it does not identify the os template.
can you help me out...:)

**Comment by ZzAntares** [comment]
Hello `amd64` and `x86_64` both refer to a 64bit platform, I've only used proxmox in a 64bit environment I can't tell you if it works with in i386.

I don't think your issue with openvz is related to the architecture (only if you were creating kvm instead), just try to use the same architecture for your container that your proxmox server has. And check if you're saving the templates in the correct folder.

Regards.

**Comment by avi123nash** [comment]
Thanks a lot...:)
